import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Report } from "@/types/report";
import { generateFormattedReport } from "@/lib/report-formatter";
import { Download, FileText, FileCode } from "lucide-react";

interface ExportOptionsProps {
  report: Report;
}

export function ExportOptions({ report }: ExportOptionsProps) {
  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadTxt = () => {
    const formatted = generateFormattedReport(report);
    const filename = `daily-report-${report.date}.txt`;
    downloadFile(formatted, filename, "text/plain");
  };

  const handleDownloadMd = () => {
    const formatted = generateFormattedReport(report);
    // Convert to markdown format with proper headers
    const markdown = `# Daily Report - ${report.date}

${formatted}

---

*Generated by Daily Report Generator*
`;
    const filename = `daily-report-${report.date}.md`;
    downloadFile(markdown, filename, "text/markdown");
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Download className="h-5 w-5" />
          Export Options
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-2">
        <Button
          variant="outline"
          className="w-full justify-start"
          onClick={handleDownloadTxt}
          aria-label="Download as text file"
        >
          <FileText className="h-4 w-4 mr-2" />
          Download as .txt
        </Button>
        <Button
          variant="outline"
          className="w-full justify-start"
          onClick={handleDownloadMd}
          aria-label="Download as markdown file"
        >
          <FileCode className="h-4 w-4 mr-2" />
          Download as .md
        </Button>
        <p className="text-xs text-muted-foreground mt-2">
          Export your report in different formats
        </p>
      </CardContent>
    </Card>
  );
}
